### ISSUE TITLE
No README or LICENSE

### ISSUE THREAD

**Issue by jrha** [quattor/dashboard#1]

**Comment by samary** [comment]
README added.
Under which Licence should this be released ?

**Comment by jrha** [comment]
Apache2? The STFC part should be, does ULB concur?

**Comment by samary** [comment]
ULB agrees with Apache 2

**Comment by jrha** [comment]
Great, agreed.

**Comment by jouvin** [comment]
README and LICENSE are in the `html` dir, they should be in the top-level dir...

**Comment by jrha** [comment]
Resolved by #2.
